# Generated by Django 3.0.5 on 2020-05-01 16:48

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=64, null=True, verbose_name='company name')),
                ('file', models.FileField(upload_to='', verbose_name='File to upload')),
                ('created_at', models.DateTimeField(default=app.models.get_utc_now, help_text='Date in format ISO8601. Example: 2020-03-03T18:31:01.915000Z.')),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=app.models.get_utc_now, help_text='Date in format ISO8601. Example: 2020-03-03T18:31:01.915000Z.')),
                ('downloader', models.ForeignKey(help_text='User that download the file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload', models.ForeignKey(help_text='User that uploaded the extension', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Upload')),
            ],
        ),
    ]
