# Generated by Django 3.0.5 on 2020-05-08 17:50

import app.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='company',
        ),
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(help_text='Select one or more files to upload', upload_to='', verbose_name='File to upload'),
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=64, verbose_name='uuid')),
                ('email', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=64, null=True, verbose_name='email address')),
                ('company', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=64, null=True, verbose_name='company')),
                ('first_name', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=64, null=True, verbose_name='last name')),
                ('last_name', models.CharField(blank=True, db_index=True, help_text='Optional', max_length=64, null=True, verbose_name='first name')),
                ('created_at', models.DateTimeField(default=app.models.get_utc_now, help_text='Date in format ISO8601. Example: 2020-03-03T18:31:01.915000Z.')),
                ('enabled', models.BooleanField(default=True, verbose_name='Link enabled')),
                ('created_by', models.ForeignKey(help_text='User that created the link', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='upload',
            name='link',
            field=models.ForeignKey(default=0, help_text='Link given for this upload', on_delete=django.db.models.deletion.PROTECT, to='app.Link'),
            preserve_default=False,
        ),
    ]
