# Generated by Django 3.0.5 on 2020-05-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200508_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='upload',
            field=models.ForeignKey(help_text='Uploaded file', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Upload'),
        ),
    ]
